# Generated by Django 4.1.13 on 2023-11-21 18:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DisneylandReview",
        ),
    ]
