# Generated by Django 4.1.13 on 2023-11-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("disneyland", "0002_disneylandreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="confirmpass",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="passWord",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="userName",
            field=models.CharField(max_length=100),
        ),
    ]
