# Generated by Django 4.1.13 on 2023-11-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("disneyland", "0003_alter_userinfo_confirmpass_alter_userinfo_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="email",
            field=models.CharField(max_length=100),
        ),
    ]
