# Generated by Django 4.1.13 on 2023-11-20 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("disneyland", "0004_alter_userinfo_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="disneylandReview",
        ),
    ]
