# Generated by Django 4.1.13 on 2023-11-20 22:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("disneyland", "0006_alter_userinfo_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userinfo",
            table=None,
        ),
    ]
