# Generated by Django 4.1.13 on 2023-11-21 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("disneyland", "0007_alter_userinfo_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinfo",
            options={"get_latest_by": "created_at"},
        ),
    ]
