# Generated by Django 4.1.13 on 2023-11-21 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("disneyland", "0008_alter_userinfo_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinfo",
            options={},
        ),
    ]
