# Generated by Django 4.1.13 on 2023-11-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("disneyland", "0009_alter_userinfo_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinfo",
            options={"get_latest_by": "created_at"},
        ),
        migrations.AddField(
            model_name="userinfo",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
