# Generated by Django 4.1.13 on 2023-11-21 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("disneyland", "0010_alter_userinfo_options_userinfo_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinfo",
            options={},
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="created_at",
        ),
    ]
