# Generated by Django 4.1.13 on 2023-11-21 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("disneyland", "0011_alter_userinfo_options_remove_userinfo_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinfo",
            options={"get_latest_by": "id"},
        ),
    ]
