# Generated by Django 4.1.13 on 2023-11-22 07:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("disneyland", "0013_disneylandreview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disneylandreview",
            name="categories",
        ),
    ]
